import com.haizhi.manage.TaskManage
import com.haizhi.kafka.KafkaClientConsumer
import org.apache.kafka.clients.consumer.ConsumerRecords
import org.apache.kafka.clients.consumer.ConsumerRecord

global com.haizhi.kafka.KafkaClientConsumer kafkaClient

rule "kafka"
when
    task: TaskManage(kafkaCount < MAX_KAFKA_NUM)
then
    ConsumerRecords<String, String> records = kafkaClient.runTask();
    for (ConsumerRecord<String, String> record : records) {
        String _record_id = record.key();
        String docJson = record.value();

        // 存入增量区
        task.addIncData(_record_id, docJson);

        // 计数增加
        task.incKafkaCount(1);
    }

    update(task)
end

rule "clean"
when
    task: TaskManage(kafkaCount >= MAX_KAFKA_NUM)
then
    System.out.println("进入清洗流程..");

    //这里把HBase中的数据从增量区读出放入全量区
    task.transfer();

    update(task)
end