import com.haizhi.manage.TaskManage
import com.haizhi.manage.DataTask

//任务管理器
//rule "manage"
//when
//    manage: TaskManage()
//then
//    manage.consumerData();
//    update(manage)
//end

//消费数据
rule "consumer"
when
    task: DataTask(status == STATUS_CONSUMER)
then
    //System.out.println("开始执行kafka状态");
    task.consumerData();
    //System.out.println("执行完成kafka状态");
end

//清洗数据
rule "clean"
when
    task: DataTask(status == STATUS_CLEAN)
then
    //System.out.println("开始执行清洗状态");
    //清理数据
    task.cleanData();

    //System.out.println("执行完成清洗状态");
end

//rule "working"
//when
//    task: DataTask(status==STATUS_WORKING)
//then
//    Thread.sleep(100);
//    update(task)
//end

//rule "cleaning"
//when
//    task: DataTask(status==STATUS_CLEANING)
//then
//    //休眠1秒 等待完成
//    Thread.sleep(100);
//    update(task)
//end